### ISSUE TITLE
Two more errors when I tried to post on cdrhrails

### ISSUE THREAD

**Issue by wkdewey** [CDRH/african_poetics#420]
```


/var/local/www/collections/african_poetics/scripts/overrides/csv_to_es_people.rb:107:in `person': undefined method `uniq' for ";;;;;;;;;[Achebe, Chinua 'Albert Chinualumogu'](apdp.person.itn.000265);;;[Peters, Lenrie](apdp.person.itn.000030);;;[Awoonor-Williams, George Kofi Nyidevu 'Kofi Awoonor'](apdp.person.itn.001046);;;[Brutus, Dennis Vincent](apdp.person.itn.000779);;;[Okigbo, Christopher](apdp.person.itn.001150);;;[Senghor, Léopold Sédar](apdp.person.itn.001141);;;[U Tam'si, Tchicaya](apdp.person.itn.000297);;;[Reed, John]();;;[Wake, Clive]();;;[Cook, David]();;;[Pieterse, Cosmo]();;;[Moore, Gerald]();;;[Brutus, Dennis Vincent](apdp.person.itn.000779);;;[Moore, Gerald]();;;[Achebe, Chinua 'Albert Chinualumogu'](apdp.person.itn.000265);;;[Okigbo, Christopher](apdp.person.itn.001150)":String (NoMethodError)

    people = get_value("related-people").uniq
                                        ^^^^^
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/es_request.rb:210:in `assemble_additional_2'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/es_request.rb:54:in `assemble_json_2'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/es_request.rb:25:in `assemble_json'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/csv_to_es.rb:39:in `create_json'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/csv_to_es.rb:30:in `initialize'
        from /var/local/www/collections/african_poetics/scripts/overrides/file_csv.rb:156:in `new'
        from /var/local/www/collections/african_poetics/scripts/overrides/file_csv.rb:156:in `row_to_es'
        from /var/local/www/collections/african_poetics/scripts/overrides/file_csv.rb:27:in `block in transform_es'
        from /usr/local/rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/csv/table.rb:939:in `each'
        from /usr/local/rvm/rubies/ruby-3.1.6/lib/ruby/3.1.0/csv/table.rb:939:in `each'
        from /var/local/www/collections/african_poetics/scripts/overrides/file_csv.rb:24:in `transform_es'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/file_type.rb:57:in `post_es'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/data_manager.rb:317:in `transform_and_post'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/data_manager.rb:126:in `block (3 levels) in batch_process_files'
error for item apdp.person.000937
posting apdp.work.000001
/var/local/www/collections/african_poetics/scripts/overrides/csv_to_es_people.rb:81:in `citation': undefined method `split' for nil:NilClass (NoMethodError)

    works = works.split(";;;") if get_value("work roles")
                 ^^^^^^
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/es_request.rb:169:in `assemble_metadata_original_2'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/es_request.rb:51:in `assemble_json_2'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/es_request.rb:25:in `assemble_json'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/csv_to_es.rb:39:in `create_json'
        from /usr/local/rvm/gems/ruby-3.1.6@datura_new/bundler/gems/datura-500edb395405/lib/datura/to_es/csv_to_es.rb:30:in `initialize'
        from /var/local/www/collections/african_poetics/scripts/overrides/file_csv.rb:156:in `new'
        from /var/local/www/collections/african_poetics/scripts/overrides/file_csv.rb:156:in `row_to_es'
        from /var/local/www/collections/african_poetics/scripts/overrides/file_csv.rb:27:in `block in transform_es'
```

**Comment by wkdewey** [comment]
Looks like only a few items. I don't know why I didn't see this before.
